versions:
    "system":
        folder: "system"
    "4.7.0":
        folder: all
    "4.4.0":
        folder: all
    "4.1.2":
        folder: all
    "3.24.34":
        folder: all
    "3.24.24":
        folder: all
